### ISSUE TITLE
Could not instantiate mail function.

### ISSUE THREAD

**Issue by cjarrodsnow** [tone4hook/contact-form-recaptcha#1]
I greatly appreciate your script for this form and I'm looking forward to using it... and I appreciate your step by step instructions.  When I set up the form, entered the information where it needed to be, then tested the form, I received the following error "I could not send the email.Could not instantiate mail function."  Is this something I incorrectly did?  Your help is appreciated.  Thank you.

**Comment by tone4hook** [comment]
Unfortunately it would be difficult for me to know exactly what is going wrong without knowing more information.Also, the server set up and how you set up your recaptcha add so many extra variations on things that can go wrong.All I can say is that I still have a version of this code as is working on a live server without issues.The only help I can provide is for you to check the following:Is the $fromEmail the server email address?Ex. info@yourdomain.comAre you using recaptcha v2?Version 1 is no longer supported.Go to the link under Acknowledgments on my repo to see the article; the author of that article might help in comments if you are more specific.Sorry I cannot give you more assistance than that.Good luck.
Sent from Yahoo Mail for iPhone


On Sunday, September 16, 2018, 7:12 AM, cjarrodsnow <notifications@github.com> wrote:


I greatly appreciate your script for this form and I'm looking forward to using it... and I appreciate your step by step instructions. When I set up the form, entered the information where it needed to be, then tested the form, I received the following error "I could not send the email.Could not instantiate mail function." Is this something I incorrectly did? Your help is appreciated. Thank you.

**Comment by cjarrodsnow** [comment]
thank you for your quick reply... I've tried everything in Google and see now the possible problems are endless lol.  I'm getting with my host provider to see if they can provide guidance.  Will definitely let you know what the issue is, in case others have the same issue in the future.  Thank you for your time.

**Comment by cjarrodsnow** [comment]
Again, thank you for getting back with me.  To keep things simple, the
issue was host side of things and I believe it was the php.ini.  Long story
short, I set up an email account with the host provider and used that
account for the "send email to," then applied a forwarding rule so all
emails get forwarded from my host email account to my google account... the
form works great! thank you for sharing this script on GitHub!
